version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: kudos_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  server:
    image: vargacska1/devops_backend:latest
    build: ./server
    container_name: kudos_server
    restart: always
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      PORT: 3000
      DB_USER: ${MONGO_ROOT_USER}
      DB_PASSWORD: ${MONGO_ROOT_PASSWORD}
      DB_URL: mongo
      DB_NAME: ${MONGO_DB_NAME}
    depends_on:
      - mongo

  client:
    image: vargacska1/devops_frontend:latest
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: kudos_client
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - server

volumes:
  mongo_data: