name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:    

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup docker build
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DO_USERNAME}}
          password: ${{secrets.DO_PASSWORD}}
      
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: vargacska1/devops_backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: vargacska1/devops_frontend:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
      

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.DO_HOST}}
          username: ${{secrets.DO_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "docker-compose.yml"
          target: "/home/${{secrets.DO_USERNAME}}/kudos-app"
      
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.DO_HOST}}
          username: ${{secrets.DO_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            mkdir -p ~/kudos-app
            cd ~/kudos-app

            echo "${{ secrets.PROD_ENV_FILE }}" > .env

            docker compose pull
            docker compose up -d --remove-orphans --force-recreate
            docker image prune -f