name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Node.js beállítása
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Frontend függőségek
        working-directory: ./client
        run: npm ci

      - name: Unit Tesztek futtatása
        working-directory: ./client
        run: npm test

      - name: Backend függőségek
        working-directory: ./server
        run: npm install

      - name: Playwright telepítése
        run: npm install -D @playwright/test && npx playwright install --with-deps

      - name: E2E Tesztek futtatása
        run: npx playwright test
